<?php

declare(strict_types=1);

namespace OCA\Employees\Migration;

/**
 * Canonical relational contract for the Employees application.
 *
 * UID columns intentionally remain strings. Every application table primary
 * key and every relation to an application entity uses an integer family.
 */
final class CanonicalSchema {
	public const APP_TABLES = [
		'absence_history', 'absence_types', 'absences', 'anniversaries',
		'clients', 'computer_inventory', 'departments', 'emergency_contacts',
		'employee_activities', 'employee_activity_areas', 'employee_file_movements',
		'employee_onboarding', 'employee_settings', 'employee_time_reports',
		'employees', 'fee_payments', 'holidays', 'human_resources',
		'inventory_models', 'inventory_movements', 'maintenance_changes',
		'maintenance_checks', 'maintenance_groups', 'maintenance_records',
		'onboarding_catalog', 'org_chart', 'org_chart_positions',
		'permission_groups', 'positions', 'professional_fees',
		'purchase_attachments', 'purchase_authorizations', 'purchase_details',
		'purchase_documents', 'purchase_history', 'purchase_orders',
		'purchase_quotes', 'purchase_requests', 'purchase_signatures',
		'purchase_suppliers', 'payroll_audit', 'payroll_employee_rules',
		'payroll_inputs', 'payroll_payments', 'payroll_periods',
		'payroll_plan_profiles', 'payroll_plans', 'payroll_payslip_lines',
		'payroll_payslips', 'payroll_rule_profiles', 'payroll_rules',
		'employee_ai_imports', 'savings_history', 'support_history', 'teams',
		'user_savings', 'vacation_bonus_payments', 'vacation_history',
	];

	/** @var array<string, string> table.column => PostgreSQL data_type */
	public const EXPECTED_TYPES = [
		'departments.id_parent' => 'integer',
		'employee_time_reports.id_employee' => 'integer',
		'human_resources.id_employee' => 'integer',
		'purchase_requests.id_employee' => 'integer',
		'purchase_requests.id_department' => 'integer',
		'purchase_requests.id_team' => 'integer',
		'purchase_authorizations.id_employee_authorizer' => 'integer',

		'employees.hire_date' => 'date',
		'employees.date_birth' => 'date',
		'employees.created_at' => 'timestamp without time zone',
		'employees.updated_at' => 'timestamp without time zone',
		'departments.created_at' => 'timestamp without time zone',
		'departments.updated_at' => 'timestamp without time zone',
		'positions.created_at' => 'timestamp without time zone',
		'positions.updated_at' => 'timestamp without time zone',
		'teams.created_at' => 'timestamp without time zone',
		'teams.updated_at' => 'timestamp without time zone',
		'emergency_contacts.created_at' => 'timestamp without time zone',
		'emergency_contacts.updated_at' => 'timestamp without time zone',
		'human_resources.created_at' => 'timestamp without time zone',
		'human_resources.updated_at' => 'timestamp without time zone',
		'user_savings.last_modified' => 'timestamp without time zone',
		'org_chart.created_at' => 'timestamp without time zone',
		'professional_fees.date_start' => 'date',
		'professional_fees.date_end' => 'date',
		'fee_payments.installment_start_date' => 'date',
		'fee_payments.installment_end_date' => 'date',
		'fee_payments.date_payment' => 'date',
		'savings_history.date_request' => 'date',
		'vacation_bonus_payments.date_payment' => 'date',
		'vacation_bonus_payments.created_at' => 'timestamp without time zone',
		'vacation_bonus_payments.updated_at' => 'timestamp without time zone',
		'vacation_history.period_start' => 'date',
		'vacation_history.period_end' => 'date',
		'vacation_history.accrued_expiration_date' => 'date',
		'vacation_history.created_at' => 'timestamp without time zone',
		'vacation_history.updated_at' => 'timestamp without time zone',
		'anniversaries.date_from' => 'date',
		'anniversaries.date_until' => 'date',
		'absence_history.date_from' => 'date',
		'absence_history.date_until' => 'date',
		'maintenance_groups.time_start' => 'time without time zone',
		'maintenance_groups.time_end' => 'time without time zone',
		'maintenance_records.time_start_scheduled' => 'time without time zone',
		'maintenance_records.time_end_scheduled' => 'time without time zone',

		'professional_fees.amount_total' => 'numeric',
		'fee_payments.amount_installment' => 'numeric',
		'savings_history.quantity_requested' => 'numeric',
		'savings_history.quantity_total' => 'numeric',
		'employees.savings_fund' => 'numeric',
		'employees.salary' => 'numeric',
		'payroll_plans.base_salary' => 'numeric',
		'payroll_plans.hourly_rate' => 'numeric',
		'payroll_plans.cost_rate' => 'numeric',
		'payroll_plans.standard_month_hours' => 'numeric',
		'payroll_plans.overtime_rate' => 'numeric',
		'payroll_rules.value' => 'numeric',
		'payroll_employee_rules.override_value' => 'numeric',
		'payroll_payslips.hours' => 'numeric',
		'payroll_payslips.overtime_hours' => 'numeric',
		'payroll_payslips.units' => 'numeric',
		'payroll_payslips.base_amount' => 'numeric',
		'payroll_payslips.gross_amount' => 'numeric',
		'payroll_payslips.deduction_amount' => 'numeric',
		'payroll_payslips.net_amount' => 'numeric',
		'payroll_payslips.paid_amount' => 'numeric',
		'payroll_payslip_lines.quantity' => 'numeric',
		'payroll_payslip_lines.rate' => 'numeric',
		'payroll_payslip_lines.amount' => 'numeric',
		'payroll_inputs.quantity' => 'numeric',
		'payroll_inputs.rate' => 'numeric',
		'payroll_inputs.amount' => 'numeric',
		'payroll_payments.amount' => 'numeric',

		'payroll_plans.effective_from' => 'date',
		'payroll_plans.effective_until' => 'date',
		'payroll_plan_profiles.effective_from' => 'date',
		'payroll_plan_profiles.effective_until' => 'date',
		'payroll_employee_rules.effective_from' => 'date',
		'payroll_employee_rules.effective_until' => 'date',
		'payroll_periods.date_from' => 'date',
		'payroll_periods.date_until' => 'date',
		'payroll_payments.payment_date' => 'date',
		'payroll_periods.created_at' => 'timestamp without time zone',
		'payroll_periods.updated_at' => 'timestamp without time zone',
		'payroll_periods.package_generated_at' => 'timestamp without time zone',
		'payroll_periods.package_status' => 'character varying',
		'payroll_periods.package_path' => 'character varying',
		'payroll_periods.package_error' => 'text',
		'payroll_payslips.created_at' => 'timestamp without time zone',
		'payroll_payslips.updated_at' => 'timestamp without time zone',
		'payroll_payslips.document_file_id' => 'bigint',
		'payroll_payslips.document_generated_at' => 'timestamp without time zone',
		'payroll_payslips.document_status' => 'character varying',
		'payroll_payslips.document_path' => 'character varying',
		'payroll_payslips.document_error' => 'text',
		'payroll_inputs.created_at' => 'timestamp without time zone',
		'payroll_inputs.updated_at' => 'timestamp without time zone',
		'payroll_payments.created_at' => 'timestamp without time zone',
		'employee_ai_imports.created_at' => 'timestamp without time zone',
		'employee_ai_imports.updated_at' => 'timestamp without time zone',
		'employee_ai_imports.expires_at' => 'timestamp without time zone',
		'employee_ai_imports.applied_at' => 'timestamp without time zone',

		'absence_types.request_file' => 'boolean',
		'absence_types.request_bonus_vacation' => 'boolean',
		'absence_types.billable' => 'boolean',
		'absence_types.private' => 'boolean',
		'clients.special' => 'boolean',
		'clients.status' => 'boolean',
		'emergency_contacts.is_primary' => 'boolean',
		'employee_activities.billable' => 'boolean',
		'employee_onboarding.status' => 'boolean',
		'holidays.official' => 'boolean',
		'onboarding_catalog.on' => 'boolean',
		'permission_groups.restricted' => 'boolean',
		'permission_groups.enabled' => 'boolean',
		'professional_fees.active' => 'boolean',
		'professional_fees.special' => 'boolean',
		'purchase_quotes.selected' => 'boolean',
		'purchase_requests.warranty' => 'boolean',
		'purchase_suppliers.active' => 'boolean',
		'savings_history.status' => 'boolean',
		'vacation_history.accrued_calculated' => 'boolean',
		'vacation_history.manually_assigned' => 'boolean',
		'payroll_rule_profiles.active' => 'boolean',
		'payroll_rules.taxable' => 'boolean',
		'payroll_rules.active' => 'boolean',
		'payroll_plans.active' => 'boolean',
		'payroll_employee_rules.enabled' => 'boolean',
		'payroll_payslip_lines.taxable' => 'boolean',
	];

	/** @var array<int, array{0:string,1:string,2:string,3:string,4:string,5:string}> */
	public const FOREIGN_KEYS = [
		['absence_history', 'absence_id', 'absences', 'absence_id', 'CASCADE', 'employees_absence_history_absence_fk'],
		['absence_history', 'absence_type_id', 'absence_types', 'absence_type_id', 'RESTRICT', 'employees_absence_history_type_fk'],
		['absences', 'id_anniversary', 'anniversaries', 'id_anniversary', 'SET NULL', 'employees_absences_anniversary_fk'],
		['clients', 'project_leader', 'employees', 'id_employees', 'SET NULL', 'employees_clients_leader_fk'],
		['clients', 'client_parent', 'clients', 'id', 'SET NULL', 'employees_clients_parent_fk'],
		['computer_inventory', 'id_employee', 'employees', 'id_employees', 'SET NULL', 'employees_inventory_employee_fk'],
		['computer_inventory', 'id_model', 'inventory_models', 'id_model', 'SET NULL', 'employees_inventory_model_fk'],
		['departments', 'id_parent', 'departments', 'id_department', 'SET NULL', 'employees_departments_parent_fk'],
		['emergency_contacts', 'id_employee', 'employees', 'id_employees', 'CASCADE', 'employees_emergency_contact_employee_fk'],
		['emergency_contacts', 'primary_employee', 'employees', 'id_employees', 'SET NULL', 'employees_emergency_contact_primary_fk'],
		['employee_activity_areas', 'id_activity', 'employee_activities', 'id_activity', 'CASCADE', 'employees_activity_area_activity_fk'],
		['employee_activity_areas', 'id_department', 'departments', 'id_department', 'CASCADE', 'employees_activity_area_department_fk'],
		['employee_file_movements', 'id_employee', 'employees', 'id_employees', 'SET NULL', 'employees_file_movement_employee_fk'],
		['employee_onboarding', 'id_employee', 'employees', 'id_employees', 'CASCADE', 'employees_onboarding_employee_fk'],
		['employee_onboarding', 'id_boarding', 'onboarding_catalog', 'id_boarding', 'CASCADE', 'employees_onboarding_catalog_fk'],
		['employee_time_reports', 'id_employee', 'employees', 'id_employees', 'CASCADE', 'employees_time_report_employee_fk'],
		['employee_time_reports', 'id_client', 'clients', 'id', 'SET NULL', 'employees_time_report_client_fk'],
		['employee_time_reports', 'id_activity', 'employee_activities', 'id_activity', 'SET NULL', 'employees_time_report_activity_fk'],
		['fee_payments', 'id_fee', 'professional_fees', 'id_fee', 'CASCADE', 'employees_fee_payment_fee_fk'],
		['human_resources', 'id_employee', 'employees', 'id_employees', 'CASCADE', 'employees_human_resources_employee_fk'],
		['inventory_movements', 'id_team', 'computer_inventory', 'id_team', 'CASCADE', 'employees_inventory_movement_device_fk'],
		['maintenance_changes', 'id_group', 'maintenance_groups', 'id', 'SET NULL', 'employees_maintenance_change_group_fk'],
		['maintenance_changes', 'id_maintenance', 'maintenance_records', 'id', 'SET NULL', 'employees_maintenance_change_record_fk'],
		['maintenance_checks', 'id_maintenance', 'maintenance_records', 'id', 'CASCADE', 'employees_maintenance_check_record_fk'],
		['maintenance_groups', 'id_department', 'departments', 'id_department', 'SET NULL', 'employees_maintenance_group_department_fk'],
		['maintenance_records', 'id_group', 'maintenance_groups', 'id', 'CASCADE', 'employees_maintenance_record_group_fk'],
		['maintenance_records', 'id_team', 'computer_inventory', 'id_team', 'CASCADE', 'employees_maintenance_record_device_fk'],
		['maintenance_records', 'id_model', 'inventory_models', 'id_model', 'SET NULL', 'employees_maintenance_record_model_fk'],
		['maintenance_records', 'id_employee', 'employees', 'id_employees', 'SET NULL', 'employees_maintenance_record_employee_fk'],
		['maintenance_records', 'id_department', 'departments', 'id_department', 'SET NULL', 'employees_maintenance_record_department_fk'],
		['org_chart', 'id_employee', 'employees', 'id_employees', 'CASCADE', 'employees_org_chart_employee_fk'],
		['org_chart', 'id_dependent', 'employees', 'id_employees', 'CASCADE', 'employees_org_chart_dependent_fk'],
		['org_chart_positions', 'id_employee', 'employees', 'id_employees', 'CASCADE', 'employees_org_position_employee_fk'],
		['professional_fees', 'id_client', 'clients', 'id', 'CASCADE', 'employees_professional_fee_client_fk'],
		['purchase_attachments', 'id_request', 'purchase_requests', 'id_request', 'CASCADE', 'employees_purchase_attachment_request_fk'],
		['purchase_authorizations', 'id_request', 'purchase_requests', 'id_request', 'CASCADE', 'employees_purchase_authorization_request_fk'],
		['purchase_authorizations', 'id_employee_authorizer', 'employees', 'id_employees', 'SET NULL', 'employees_purchase_authorization_employee_fk'],
		['purchase_details', 'id_request', 'purchase_requests', 'id_request', 'CASCADE', 'employees_purchase_detail_request_fk'],
		['purchase_documents', 'id_request', 'purchase_requests', 'id_request', 'CASCADE', 'employees_purchase_document_request_fk'],
		['purchase_history', 'id_request', 'purchase_requests', 'id_request', 'CASCADE', 'employees_purchase_history_request_fk'],
		['purchase_orders', 'id_request', 'purchase_requests', 'id_request', 'CASCADE', 'employees_purchase_order_request_fk'],
		['purchase_orders', 'id_supplier', 'purchase_suppliers', 'id_supplier', 'SET NULL', 'employees_purchase_order_supplier_fk'],
		['purchase_quotes', 'id_request', 'purchase_requests', 'id_request', 'CASCADE', 'employees_purchase_quote_request_fk'],
		['purchase_quotes', 'id_supplier', 'purchase_suppliers', 'id_supplier', 'SET NULL', 'employees_purchase_quote_supplier_fk'],
		['purchase_requests', 'id_employee', 'employees', 'id_employees', 'SET NULL', 'employees_purchase_request_employee_fk'],
		['purchase_requests', 'id_department', 'departments', 'id_department', 'SET NULL', 'employees_purchase_request_department_fk'],
		['purchase_requests', 'id_team', 'teams', 'id_team', 'SET NULL', 'employees_purchase_request_team_fk'],
		['purchase_requests', 'id_client', 'clients', 'id', 'SET NULL', 'employees_purchase_request_client_fk'],
		['purchase_requests', 'selected_supplier', 'purchase_suppliers', 'id_supplier', 'SET NULL', 'employees_purchase_request_supplier_fk'],
		['purchase_signatures', 'id_request', 'purchase_requests', 'id_request', 'CASCADE', 'employees_purchase_signature_request_fk'],
		['support_history', 'id_team', 'computer_inventory', 'id_team', 'CASCADE', 'employees_support_device_fk'],
		['payroll_rules', 'profile_id', 'payroll_rule_profiles', 'id', 'CASCADE', 'payroll_rule_profile_fk'],
		['payroll_plans', 'employee_id', 'employees', 'id_employees', 'RESTRICT', 'payroll_plan_employee_fk'],
		['payroll_plan_profiles', 'plan_id', 'payroll_plans', 'id', 'CASCADE', 'payroll_plan_profile_plan_fk'],
		['payroll_plan_profiles', 'profile_id', 'payroll_rule_profiles', 'id', 'CASCADE', 'payroll_plan_profile_profile_fk'],
		['payroll_employee_rules', 'employee_id', 'employees', 'id_employees', 'RESTRICT', 'payroll_employee_rule_employee_fk'],
		['payroll_employee_rules', 'rule_id', 'payroll_rules', 'id', 'CASCADE', 'payroll_employee_rule_rule_fk'],
		['payroll_payslips', 'period_id', 'payroll_periods', 'id', 'RESTRICT', 'payroll_payslip_period_fk'],
		['payroll_payslips', 'employee_id', 'employees', 'id_employees', 'RESTRICT', 'payroll_payslip_employee_fk'],
		['payroll_payslips', 'plan_id', 'payroll_plans', 'id', 'SET NULL', 'payroll_payslip_plan_fk'],
		['payroll_payslip_lines', 'payslip_id', 'payroll_payslips', 'id', 'CASCADE', 'payroll_payslip_line_slip_fk'],
		['payroll_inputs', 'period_id', 'payroll_periods', 'id', 'CASCADE', 'payroll_input_period_fk'],
		['payroll_inputs', 'employee_id', 'employees', 'id_employees', 'RESTRICT', 'payroll_input_employee_fk'],
		['payroll_payments', 'period_id', 'payroll_periods', 'id', 'RESTRICT', 'payroll_payment_period_fk'],
		['payroll_payments', 'payslip_id', 'payroll_payslips', 'id', 'RESTRICT', 'payroll_payment_payslip_fk'],
		['payroll_payments', 'employee_id', 'employees', 'id_employees', 'RESTRICT', 'payroll_payment_employee_fk'],
		['vacation_bonus_payments', 'id_employee', 'employees', 'id_employees', 'CASCADE', 'employees_vacation_bonus_employee_fk'],
		['vacation_history', 'id_employee', 'employees', 'id_employees', 'CASCADE', 'employees_vacation_history_employee_fk'],
	];
}
